import type { Book } from "../features/books/bookTypes";

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
    status: "completed",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-01-10",
  },
  {
    id: "2",
    title: "Deep Work",
    author: "Cal Newport",
    category: "Productivity",
    status: "reading",
    rating: 4,
    isFavorite: true,
    createdAt: "2026-02-15",
  },
  {
    id: "3",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    status: "completed",
    rating: 5,
    isFavorite: false,
    createdAt: "2026-03-01",
  },
  {
    id: "4",
    title: "Think Again",
    author: "Adam Grant",
    category: "Psychology",
    status: "to-read",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-03-20",
  },
  {
    id: "5",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    category: "Finance",
    status: "to-read",
    rating: 4,
    isFavorite: true,
    createdAt: "2026-04-01",
  },
  {
    id: "6",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "Self-Help",
    status: "completed",
    rating: 4,
    isFavorite: true,
    createdAt: "2026-01-25",
  },
  {
    id: "7",
    title: "Start With Why",
    author: "Simon Sinek",
    category: "Business",
    status: "reading",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-02-05",
  },
  {
    id: "8",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "History",
    status: "completed",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-01-18",
  },
  {
    id: "9",
    title: "Can't Hurt Me",
    author: "David Goggins",
    category: "Biography",
    status: "reading",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-03-10",
  },
  {
    id: "10",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Finance",
    status: "completed",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-02-28",
  },
  {
    id: "11",
    title: "Ikigai",
    author: "Héctor García",
    category: "Self-Help",
    status: "to-read",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-04-10",
  },
  {
    id: "12",
    title: "Zero to One",
    author: "Peter Thiel",
    category: "Business",
    status: "completed",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-03-05",
  },
  {
    id: "13",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Psychology",
    status: "reading",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-04-02",
  },
  {
    id: "14",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    category: "Self-Help",
    status: "completed",
    rating: 5,
    isFavorite: true,
    createdAt: "2026-01-30",
  },
  {
    id: "15",
    title: "Meditations",
    author: "Marcus Aurelius",
    category: "Philosophy",
    status: "to-read",
    rating: 4,
    isFavorite: false,
    createdAt: "2026-04-12",
  },
];
